##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://erholmes.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /ncdctest
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder

##########
# SITE SETTINGS
#
# title of site appears in banner
title: She Changed the World
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: North Carolina Women Breaking Barriers
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "NC Digital Collections - Demo She Changed the World collection" 
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: "SLNC, SANC"
# Organization branding
organization-name: "State Library of North Carolina, State Archives of North Carolina"
organization-link: https://digital.ncdcr.gov
organization-logo-banner: https://digital.ncdcr.gov/customizations/global/images/NCDCWebsiteLogo.png
organization-logo-nav: https://digital.ncdcr.gov/customizations/global/images/NCDCWebsiteLogo.png

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: cb_metadata_sctwnc
# contentdm collection name, matches collection ID used by CDM
cdm-collection-id: p16062coll6
# CONTENTdm server url
cdm-url: https://digital.ncdcr.gov
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'cb_metadata_sctwnc'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
